---
- hosts: localhost
  tasks:
    - name: "install package"
      yum:
        name: httpd
        state: present

    - name: "create user"
      user:
        name: "simi"
        state: present
...
